version: "3.9"
name: "location-service"

volumes:
  local_location_code: {}
  local_redis_data: {}
  local_sql_data: {}
  
services:
  location.service:
    image: "location.service:1.0"
    container_name: "location.api"
    build: .
    ports:
      - "7010:5000"
      - "7011:5001"
    volumes:
      - "local_location_code:/code"
    restart: on-failure
    depends_on:
      - redis
      - sql   
  redis:
    container_name: "location.redis"
    hostname: "location.redis"
    image: redis
    ports:
      - "7001:6379"
    volumes:
      - "local_redis_data:/data"
  sql:
    container_name: "location.mssql"
    hostname: "location.mssql"
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "7000:1433"
    volumes:
      - "local_sql_data:/data"
    environment:
      MSSQL_SA_PASSWORD: "Password.1"
      ACCEPT_EULA: "Y"
